### ISSUE TITLE
 Cardinal Mobile SDK  Problem

### ISSUE THREAD

**Issue by Jake-Jiang** [braintree/braintree_android#540]
![image](https://user-images.githubusercontent.com/58160182/163091291-b8cae6d3-dd7e-41b7-a3d6-b7043ca7a301.png)

when I use  braintree  4.10.0  ,it make my appsflyer sdk not work in release apk, but  when I use  4.9.0,  my appsflyer sdk works well,I'm guessing it's a problem with the Cardinal Mobile SDK.

**Comment by sarahkoop** [comment]
Also - can you confirm if you are seeing compile issues related to the `isValidated` function of the Validate response? Or, can you expand on the issue that you are seeing?

**Comment by Jake-Jiang** [comment]
2022-04-14 09:10:13.416 14499-14807/? E/AppsFlyer_6.5.0: No static method values(D)D in class Lcom/appsflyer/internal/l; or its super classes (declaration of 'com.appsflyer.internal.l' appears in base.apk)
java.lang.NoSuchMethodError: No static method values(D)D in class Lcom/appsflyer/internal/l; or its super classes (declaration of 'com.appsflyer.internal.l' appears in /data/app/base.apk)
at com.appsflyer.internal.t.AFInAppEventParameterName(:217)
at com.appsflyer.internal.p.AFInAppEventParameterName(:206)
at com.appsflyer.internal.t.AFKeystoreWrapper(:846)
at com.appsflyer.internal.p.AFInAppEventParameterName(:194)
at com.appsflyer.internal.r.valueOf(:618)
at com.appsflyer.internal.p.AFInAppEventParameterName(:190)
at com.appsflyer.internal.t.AFKeystoreWrapper(:846)
at com.appsflyer.internal.p.AFInAppEventParameterName(:194)
at com.appsflyer.internal.t.AFKeystoreWrapper(:846)
at com.appsflyer.internal.t.toString(:815)
at com.appsflyer.internal.o.AFKeystoreWrapper(:32)
at java.lang.reflect.Method.invoke(Native Method)
at com.appsflyer.internal.ah$b.run(:46)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at com.appsflyer.internal.k$4$4.run(:2)
at java.lang.Thread.run(Thread.java:920)

**Comment by Jake-Jiang** [comment]
Hello ,I'am get this error in release apk with set minifyEnabled true when I use 4.10.0, if set set minifyEnabled false or use 4.9.0,it works well

**Comment by sarahkoop** [comment]
Hi @Jake-Jiang Hmm... I don't see anything pointing to the Braintree or Cardinal SDK in that stack trace - can you explain where you see the error coming from this SDK?

**Comment by Jake-Jiang** [comment]
@sarahkoop  2.2.6-2 released, could you   update  SDK to use it ?

**Comment by Pingapplepie** [comment]
> Also - can you confirm if you are seeing compile issues related to the `isValidated` function of the Validate response? Or, can you expand on the issue that you are seeing?

I also see Cardinal released 2.2.6-2 just to fix the "isValidated" function: https://cardinaldocs.atlassian.net/wiki/spaces/CMSDK/pages/11862033/Cardinal+Mobile+SDK+-+Android

**Comment by sshropshire** [comment]
@Jake-Jiang version [4.12.0](https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#4120) now uses version `2.2.6-2` of Cardinal. Is this issue resolved?
